sudo: false
language: node_js
node_js:
- stable
script:
- npm test
after_success:
- npm run report-coverage


deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJWPWC5DP7W37ZTUA
  secret_access_key:
    secure: "qDKuIQ3Us4R1dbcewVfpJhYJcw3DJIb+M4ESW9fnkT31QvvizajIUaork1KJXM8bCFVtWnVW/sY0M+65grX2wlZuIdcUcCbk4arI4A1T0nCZf5w2uzqWTO6ZURii+5AwdfHLYijb/zs4GVnc3e24S4O4sXCkX2NDop4KV7TdLsLiVRNn11PLvJURve+8QIwh2lttWD2TmUIy2WZ4KNgUdAnn34cqJnf59yu5Kq/TFzL1QyiaGNU4sawFhWnCoHLfb/62if0qxyFCjR0hRffeXjdCSNfYie18fhP8CaYlJ8La588JodyXSKEajJ9L+N6f7aYhqmBqVK2T61WuU2W3L5NOvG2ebZ3ZWZpJ7DLdLVzAWOsODHapdw94XaFkhVi0tGWzz3E5Mo3BODmJ7uebBFtSOFO1ZuFGr0JWmnPtXZ/Dyd7A5JGwnk8oydEsrvvlw3JAHLoF3onYl2X2n/Rbilj9VNklezDvO0LqXopES/LLwS9fo1+e4XhbTjBAbQobM5+Q4n12bPVlUgONcueZ7Qi7DJWyxxpH5WNpWSps+sL68UUpLEsFfBTF9NpsAwFEna4NBM5HJwD5dcgXg+gooUEyItpOWJvNJhG00QwxBsTVdqBGdNj23HNgJEsn9NnB0/5oaSOMXim6keSIYerqmGqtlf8SkQHN0jzihSw/mKA="
  region: "us-west-2"
  app: "puzzle"
  env: "LowCost-env"
